version: '3'
services:
  express-app:
    image: my_express_app
    ports:
      - "3001:3000"
    networks:
      - express-app_my-network
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - express-app_my-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - express-app_my-network
networks:
  express-app_my-network:
    driver: bridge

